<script setup>
import {onMounted,ref} from 'vue';
import {Clock3,RefreshCw,ArrowRight} from 'lucide-vue-next';
import {useAuthStore} from '~/stores/api/auth';
import {useTutorInsightsStore} from '~/stores/api/tutorInsights';
import {canAccessPage} from '~/utils/roles';
definePageMeta({layout:'default'});
const auth=useAuthStore(),store=useTutorInsightsStore(),ready=ref(false);
const label={draft:'Draft',review:'Menunggu Review',active:'Aktif',rejected:'Ditolak'};
const tone={draft:'bg-surface-container text-outline',review:'bg-soft-orange text-on-secondary-container',active:'bg-success-soft text-success-emerald',rejected:'bg-danger-soft text-danger-rose'};
onMounted(async()=>{auth.initializeAuth();if(!auth.token)return navigateTo('/login');const user=await auth.fetchCurrentUser();if(Number(user?.role)!==3||!canAccessPage(user?.role,'moderation.own'))return navigateTo('/dashboard');ready.value=true;await store.fetchSection('moderation');});
</script>
<template><div v-if="ready" class="mx-auto w-full max-w-[1450px] min-w-0 px-4 py-5 sm:px-6 lg:px-8"><header class="mb-5 flex items-center justify-between gap-3"><div><h1 class="font-headline-md text-headline-md">Status Moderasi</h1><p class="text-sm text-on-surface-variant">Pantau status soal dan materi yang kamu buat.</p></div><button class="text-primary-container" aria-label="Muat ulang" @click="store.fetchSection('moderation')"><RefreshCw class="h-4 w-4"/></button></header><div v-if="store.error" role="alert" class="mb-4 rounded-2xl bg-danger-soft p-4 text-danger-rose">{{ store.error }}</div><div v-if="store.loading" class="space-y-3"><div v-for="n in 3" :key="n" class="h-24 animate-pulse rounded-2xl bg-surface-container"/></div><section v-else class="space-y-3"><div v-if="!store.moderation.length" class="rounded-3xl border border-soft-blue bg-surface-white p-8 text-center"><Clock3 class="mx-auto mb-3 h-10 w-10 text-primary-container"/><p class="font-semibold">Belum ada konten</p><NuxtLink to="/my-questions/create" class="mt-3 inline-block text-sm text-primary-container">Tambah Soal <ArrowRight class="inline h-4 w-4"/></NuxtLink></div><article v-for="item in store.moderation" :key="`${item.type}-${item.id}`" class="rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm"><div class="flex flex-wrap justify-between gap-2"><span class="text-xs text-on-surface-variant">{{ item.type }} · {{ item.submitted_at?new Date(item.submitted_at).toLocaleDateString('id-ID'):new Date(item.created_at).toLocaleDateString('id-ID') }}</span><span class="rounded-full px-2.5 py-1 text-xs" :class="tone[item.status]">{{ label[item.status] }}</span></div><p class="mt-3 line-clamp-3 font-semibold">{{ item.title }}</p><p v-if="item.status==='rejected'&&item.rejection_reason" class="mt-3 rounded-xl bg-danger-soft p-3 text-sm text-danger-rose"><strong>Alasan Penolakan:</strong> {{ item.rejection_reason }}</p><NuxtLink v-if="['draft','rejected'].includes(item.status)" :to="item.type==='Materi'?'/my-materials':'/my-questions'" class="mt-3 inline-flex items-center gap-1 text-sm text-primary-container">{{ item.type==='Materi'?'Kelola materi':'Edit atau kirim ulang' }} <ArrowRight class="h-4 w-4"/></NuxtLink></article></section></div></template>
