<script setup>
import {computed,onMounted,ref} from 'vue';
import {BookOpenCheck,LibraryBig,CircleCheck,Clock3,CircleX,RefreshCw} from 'lucide-vue-next';
import {useAuthStore} from '~/stores/api/auth';
import {useTutorInsightsStore} from '~/stores/api/tutorInsights';
import {canAccessPage} from '~/utils/roles';
definePageMeta({layout:'default'});
const auth=useAuthStore(),store=useTutorInsightsStore(),ready=ref(false);
const cards=computed(()=>[{label:'Total Soal Dibuat',value:store.analytics?.total_questions,icon:BookOpenCheck},{label:'Total Materi Dibuat',value:store.analytics?.total_materials,icon:LibraryBig},{label:'Approved Content',value:(store.analytics?.approved_questions||0)+(store.analytics?.active_materials||0),icon:CircleCheck},{label:'Pending Review',value:store.analytics?.pending_questions,icon:Clock3},{label:'Rejected Content',value:store.analytics?.rejected_questions,icon:CircleX}]);
onMounted(async()=>{auth.initializeAuth();if(!auth.token)return navigateTo('/login');const user=await auth.fetchCurrentUser();if(Number(user?.role)!==3||!canAccessPage(user?.role,'analytics.own'))return navigateTo('/dashboard');ready.value=true;await store.fetchSection('analytics');});
</script>
<template><div v-if="ready" class="mx-auto w-full max-w-[1450px] min-w-0 px-4 py-5 sm:px-6 lg:px-8"><header class="mb-5 flex items-center justify-between gap-3"><div><h1 class="font-headline-md text-headline-md">Analytics Kontribusi</h1><p class="text-sm text-on-surface-variant">Ringkasan konten yang kamu buat di MatrIQ.</p></div><button class="text-primary-container" aria-label="Muat ulang" @click="store.fetchSection('analytics')"><RefreshCw class="h-4 w-4"/></button></header><p v-if="store.error" role="alert" class="mb-4 rounded-2xl bg-danger-soft p-3 text-danger-rose">{{ store.error }}</p><section class="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><article v-for="card in cards" :key="card.label" class="rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm"><span class="mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-pale-blue text-primary-container"><component :is="card.icon" class="h-5 w-5"/></span><p class="text-xs text-on-surface-variant">{{ card.label }}</p><div v-if="store.loading" class="mt-2 h-7 w-16 animate-pulse rounded-lg bg-surface-container"/><strong v-else class="font-title-md text-title-md">{{ card.value??'—' }}</strong></article></section><section class="rounded-3xl border border-soft-blue bg-surface-white p-5 shadow-sm"><h2 class="mb-4 font-title-md text-title-md">Subtes Paling Banyak Dibuat</h2><p v-if="!store.analytics?.top_subtests?.length" class="text-sm text-on-surface-variant">Belum ada soal.</p><div v-else class="space-y-3"><div v-for="item in store.analytics.top_subtests" :key="item.subtest" class="flex items-center gap-3 text-sm"><span class="w-10 font-semibold">{{ item.subtest }}</span><div class="h-2 flex-1 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{width:`${100*item.total/Math.max(1,store.analytics.top_subtests[0].total)}%`}"/></div><span>{{ item.total }} soal</span></div></div></section><p v-if="store.analytics?.notice" class="mt-4 rounded-2xl bg-pale-blue p-4 text-sm text-primary-container">{{ store.analytics.notice }}</p></div></template>
