<script setup>
import { computed, onMounted, ref } from 'vue';
import { Activity, Trophy, ChartNoAxesCombined, ClipboardList, Plus, Target, TrendingUp, TrendingDown, Sparkles, Eye, Pencil, Trash2, RefreshCw } from 'lucide-vue-next';
import { useUserTryoutRecapStore } from '~/stores/api/userTryoutRecap';

const store = useUserTryoutRecapStore();
const mode = ref('latest');
const detail = ref(null);
const deleting = ref(null);
const card = 'min-w-0 rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-6';
const score = value => value == null ? '—' : new Intl.NumberFormat('id-ID', { maximumFractionDigits: 1 }).format(value);
const date = value => value ? new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : '—';
const summaryCards = computed(() => [
  { label: 'Skor Terakhir', value: store.summary?.latest_score, icon: Activity },
  { label: 'Skor Terbaik', value: store.summary?.best_score, icon: Trophy },
  { label: 'Rata-rata Skor', value: store.summary?.average_score, icon: ChartNoAxesCombined },
  { label: 'Total Rekap', value: store.summary?.total_recap ?? 0, icon: ClipboardList, count: true },
]);
const targetPercent = computed(() => store.target?.target_score && store.summary?.latest_score != null ? Math.min(100, Math.max(0, store.summary.latest_score / store.target.target_score * 100)) : 0);
const subtests = computed(() => store.subtestPerformance.map(row => ({ ...row, value: mode.value === 'latest' ? row.latest_score : row.average_score })));
const ranked = computed(() => subtests.value.filter(row => row.value != null).sort((a, b) => b.value - a.value));
const linePoints = computed(() => {
  const rows = store.scoreTrend;
  if (!rows.length) return [];
  const values = rows.map(row => Number(row.total_score));
  const min = Math.max(0, Math.floor(Math.min(...values) / 50) * 50 - 50);
  const max = Math.min(1000, Math.ceil(Math.max(...values) / 50) * 50 + 50);
  return rows.map((row, index) => ({ ...row, x: rows.length === 1 ? 50 : 6 + index * 88 / (rows.length - 1), y: 85 - (Number(row.total_score) - min) / Math.max(1, max - min) * 70 }));
});
const line = computed(() => linePoints.value.map(point => `${point.x},${point.y}`).join(' '));
async function reload() { await Promise.all([store.fetchOverview(), store.fetchHistory()]); }
async function openDetail(id) { detail.value = await store.fetchDetail(id); }
async function remove() {
  if (!deleting.value) return;
  const done = await store.deleteRecap(deleting.value.recap_id);
  if (done) { deleting.value = null; detail.value = null; await reload(); }
}
onMounted(reload);
</script>

<template>
  <div class="mx-auto w-full max-w-[1600px] min-w-0 px-4 py-5 text-on-surface sm:px-6 sm:py-7 lg:px-8">
    <header class="mb-5 flex flex-wrap items-start justify-between gap-3"><div><div class="inline-flex items-center gap-2 rounded-full bg-pale-blue px-3 py-1 text-xs font-semibold text-primary-container"><ClipboardList class="h-4 w-4" /> Evaluasi skor eksternal</div><h1 class="mt-3 text-2xl font-bold sm:text-3xl">Rekap Tryout</h1><p class="mt-1 max-w-2xl text-sm text-on-surface-variant">Catat hasil tryout dari berbagai platform dan pantau perkembangan skormu menuju target SNBT.</p></div><NuxtLink to="/tryout-recap/create" class="inline-flex items-center gap-2 rounded-xl bg-primary-container px-4 py-2.5 text-sm font-semibold text-white"><Plus class="h-4 w-4" /> Tambah Rekap</NuxtLink></header>
    <div v-if="store.error" role="alert" class="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-white p-4 text-sm text-rose-700"><span>{{ store.error }}</span><button class="inline-flex items-center gap-2 font-semibold" @click="reload"><RefreshCw class="h-4 w-4" /> Coba Lagi</button></div>
    <div v-if="store.isLoading && !store.summary" class="space-y-4" aria-label="Memuat rekap"><div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="i in 4" :key="i" class="h-28 animate-pulse rounded-3xl bg-slate-200" /></div><div class="h-64 animate-pulse rounded-3xl bg-slate-200" /><div class="h-64 animate-pulse rounded-3xl bg-slate-200" /></div>
    <template v-else>
      <section class="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><article v-for="item in summaryCards" :key="item.label" :class="card"><component :is="item.icon" class="mb-3 h-5 w-5 text-primary-container" /><p class="text-xs text-outline">{{ item.label }}</p><strong class="mt-1 block text-xl">{{ item.count ? item.value : score(item.value) }}</strong></article></section>
      <div v-if="store.summary?.score_delta != null" class="mb-5 flex items-center gap-2 text-sm font-semibold" :class="store.summary.score_delta >= 0 ? 'text-success' : 'text-orange-600'"><TrendingUp v-if="store.summary.score_delta >= 0" class="h-4 w-4" /><TrendingDown v-else class="h-4 w-4" />{{ store.summary.score_delta >= 0 ? 'Naik' : 'Turun' }} {{ score(Math.abs(store.summary.score_delta)) }} poin dari rekap sebelumnya</div>
      <div v-if="!store.summary?.total_recap" :class="card" class="mb-5 text-center"><ClipboardList class="mx-auto h-9 w-9 text-primary-container" /><h2 class="mt-3 text-lg font-bold">Belum ada rekap tryout.</h2><p class="mt-1 text-sm text-on-surface-variant">Catat hasil tryout pertamamu untuk mulai melihat perkembangan skor.</p><NuxtLink to="/tryout-recap/create" class="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary-container px-4 py-2 text-sm font-semibold text-white"><Plus class="h-4 w-4" />Tambah Rekap</NuxtLink></div>
      <div class="mb-5 grid gap-4 xl:grid-cols-12"><section :class="card" class="xl:col-span-4"><div class="mb-4 flex items-center gap-2"><Target class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Target Utama</h2></div><template v-if="store.target?.target_score"><p class="text-xs text-outline">Pilihan 1</p><h3 class="mt-1 font-semibold">{{ store.target.campus || 'Kampus belum dipilih' }}</h3><p class="text-sm text-on-surface-variant">{{ store.target.program || 'Program belum dipilih' }}</p><div class="mt-5 grid grid-cols-3 gap-2 text-sm"><div><p class="text-xs text-outline">Target</p><strong>{{ score(store.target.target_score) }}</strong></div><div><p class="text-xs text-outline">Terakhir</p><strong>{{ score(store.summary?.latest_score) }}</strong></div><div><p class="text-xs text-outline">Selisih</p><strong>{{ store.target.gap == null ? '—' : store.target.gap === 0 ? 'Tercapai 🎉' : `${score(store.target.gap)} poin` }}</strong></div></div><div class="mt-4 h-3 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${targetPercent}%` }" /></div></template><div v-else class="text-sm text-on-surface-variant"><p>Belum ada target skor. Atur target kampus dan skor untuk melihat progress menuju pilihanmu.</p><NuxtLink to="/profile" class="mt-3 inline-block font-semibold text-primary-container">Atur Target</NuxtLink></div></section>
      <section :class="card" class="xl:col-span-8"><div class="mb-4 flex items-center gap-2"><ChartNoAxesCombined class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Perkembangan Skor</h2></div><div v-if="linePoints.length" class="overflow-x-auto"><svg viewBox="0 0 100 100" preserveAspectRatio="none" class="h-52 w-full min-w-[320px] overflow-visible" role="img" aria-label="Grafik perkembangan skor"><line x1="0" y1="85" x2="100" y2="85" stroke="#dbeafe" stroke-width=".5" /><polyline v-if="linePoints.length > 1" :points="line" fill="none" stroke="#2563eb" stroke-width="1.2" vector-effect="non-scaling-stroke" /><g v-for="point in linePoints" :key="point.recap_id"><circle :cx="point.x" :cy="point.y" r="1.6" fill="#2563eb"><title>{{ date(point.recap_at) }} · {{ point.platform || 'Platform tidak diketahui' }} · {{ point.tryout_name || 'Tryout' }} · {{ score(point.total_score) }}{{ point.delta == null ? '' : ` (${point.delta >= 0 ? '+' : ''}${score(point.delta)})` }}</title></circle></g></svg><div class="flex justify-between text-xs text-outline"><span>{{ date(store.scoreTrend[0]?.recap_at) }}</span><span>{{ date(store.scoreTrend.at(-1)?.recap_at) }}</span></div></div><p v-else class="py-12 text-center text-sm text-outline">Grafik muncul setelah rekap pertama ditambahkan.</p></section></div>
      <div class="mb-5 grid gap-4 xl:grid-cols-12"><section :class="card" class="xl:col-span-8"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 class="font-bold">Performa Subtes</h2><div class="rounded-xl bg-surface-container-low p-1 text-xs"><button class="rounded-lg px-3 py-1.5" :class="mode === 'latest' ? 'bg-primary-container text-white' : ''" @click="mode = 'latest'">Skor Terakhir</button><button class="rounded-lg px-3 py-1.5" :class="mode === 'average' ? 'bg-primary-container text-white' : ''" @click="mode = 'average'">Rata-rata</button></div></div><div v-for="row in subtests" :key="row.code" class="mb-3 grid grid-cols-[36px_1fr_48px] items-center gap-3 text-sm"><span class="font-semibold">{{ row.code }}</span><div class="h-3 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${Math.min(100, Math.max(0, (row.value || 0) / 10))}%` }" /></div><span class="text-right">{{ score(row.value) }}</span></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-pale-blue p-3"><p class="text-xs text-outline">Subtes Terkuat</p><strong class="mt-1 block">{{ ranked[0]?.code || '—' }} · {{ score(ranked[0]?.value) }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Subtes Perlu Fokus</p><strong class="mt-1 block">{{ ranked.at(-1)?.code || '—' }} · {{ score(ranked.at(-1)?.value) }}</strong></div></div></section><section :class="card" class="xl:col-span-4"><h2 class="mb-4 font-bold">Platform yang Sering Digunakan</h2><p v-if="!store.platformUsage.length" class="text-sm text-outline">Belum ada platform tercatat.</p><div v-for="(row, index) in store.platformUsage" :key="row.platform" class="mb-3"><div class="flex justify-between gap-2 text-sm"><span>{{ index + 1 }}. {{ row.platform }}</span><strong>{{ row.total }} rekap</strong></div><div class="mt-1 h-2 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${row.total / store.platformUsage[0].total * 100}%` }" /></div></div></section></div>
      <section v-if="store.insights.length" :class="card" class="mb-5"><div class="mb-3 flex items-center gap-2"><Sparkles class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Insight untukmu</h2></div><p v-for="insight in store.insights" :key="insight" class="py-1 text-sm text-on-surface-variant">{{ insight }}</p></section>
      <section :class="card"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 class="font-bold">Riwayat Rekap</h2><span class="text-xs text-outline">{{ store.pagination.total }} rekap</span></div><div v-if="store.recaps.length" class="hidden overflow-x-auto md:block"><table class="w-full min-w-[700px] text-left text-sm"><thead class="border-b border-soft-blue text-outline"><tr><th class="p-3">Tanggal</th><th class="p-3">Platform</th><th class="p-3">Nama Tryout</th><th class="p-3">Total Score</th><th class="p-3">Perubahan</th><th class="p-3">Aksi</th></tr></thead><tbody><tr v-for="row in store.recaps" :key="row.recap_id" class="border-b border-soft-blue"><td class="p-3">{{ date(row.recap_at) }}</td><td class="p-3">{{ row.platform || '—' }}</td><td class="p-3">{{ row.tryout_name || '—' }}</td><td class="p-3 font-semibold">{{ score(row.total_score) }} <span v-if="row.total_score === store.summary?.best_score" class="text-xs text-primary-container">Terbaik</span></td><td class="p-3">{{ row.delta == null ? '—' : `${row.delta >= 0 ? '+' : ''}${score(row.delta)}` }}</td><td class="p-3"><div class="flex gap-2"><button :aria-label="`Lihat rekap ${row.recap_id}`" @click="openDetail(row.recap_id)"><Eye class="h-4 w-4" /></button><NuxtLink :to="`/tryout-recap/${row.recap_id}`" :aria-label="`Edit rekap ${row.recap_id}`"><Pencil class="h-4 w-4" /></NuxtLink><button :aria-label="`Hapus rekap ${row.recap_id}`" class="text-rose-600" @click="deleting = row"><Trash2 class="h-4 w-4" /></button></div></td></tr></tbody></table></div><div class="space-y-3 md:hidden"><article v-for="row in store.recaps" :key="row.recap_id" class="rounded-2xl border border-soft-blue p-3 text-sm"><div class="flex justify-between gap-2"><strong>{{ row.platform || 'Platform tidak diketahui' }}</strong><strong>{{ score(row.total_score) }}</strong></div><p class="mt-1 text-xs text-outline">{{ row.tryout_name || '—' }} · {{ date(row.recap_at) }}</p><div class="mt-3 flex gap-4 text-primary-container"><button @click="openDetail(row.recap_id)">Detail</button><NuxtLink :to="`/tryout-recap/${row.recap_id}`">Edit</NuxtLink><button class="text-rose-600" @click="deleting = row">Hapus</button></div></article></div><p v-if="!store.recaps.length" class="py-8 text-center text-sm text-outline">Belum ada riwayat rekap.</p><div v-if="store.pagination.total_pages > 1" class="mt-4 flex items-center justify-end gap-3 text-sm"><button :disabled="store.pagination.page <= 1" @click="store.fetchHistory(store.pagination.page - 1)">Sebelumnya</button><span>{{ store.pagination.page }} / {{ store.pagination.total_pages }}</span><button :disabled="store.pagination.page >= store.pagination.total_pages" @click="store.fetchHistory(store.pagination.page + 1)">Berikutnya</button></div></section>
    </template>
    <div v-if="detail" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="detail = null"><div role="dialog" aria-modal="true" class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-5 shadow-xl"><div class="flex justify-between"><h2 class="text-lg font-bold">Detail Rekap</h2><button @click="detail = null">Tutup</button></div><p class="mt-4 text-sm text-outline">{{ date(detail.recap_at) }} · {{ detail.platform }}</p><h3 class="font-semibold">{{ detail.tryout_name || 'Tryout eksternal' }}</h3><div class="mt-4 grid grid-cols-2 gap-2 text-sm"><div v-for="code in ['pu','ppu','pbm','pk','lbi','lbe','pm']" :key="code" class="flex justify-between rounded-xl bg-surface-container-low p-2"><span>{{ code.toUpperCase() }}</span><strong>{{ score(detail[code]) }}</strong></div></div><p class="mt-4 font-bold">Total Score: {{ score(detail.total_score) }}</p><p v-if="detail.notes" class="mt-2 whitespace-pre-wrap text-sm text-on-surface-variant">{{ detail.notes }}</p></div></div>
    <div v-if="deleting" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="deleting = null"><div role="alertdialog" aria-modal="true" class="w-full max-w-sm rounded-3xl bg-white p-5 shadow-xl"><h2 class="font-bold">Hapus rekap?</h2><p class="mt-2 text-sm text-on-surface-variant">Rekap {{ deleting.tryout_name || deleting.platform }} akan dihapus.</p><div class="mt-5 flex justify-end gap-3"><button @click="deleting = null">Batal</button><button :disabled="store.isSaving" class="rounded-xl bg-rose-600 px-4 py-2 text-sm font-semibold text-white" @click="remove">Hapus</button></div></div></div>
  </div>
</template>
