<script setup>
import {onMounted,ref} from 'vue';
import {TrendingUp,RefreshCw} from 'lucide-vue-next';
import {useAuthStore} from '~/stores/api/auth';
import {useTutorInsightsStore} from '~/stores/api/tutorInsights';
import {canAccessPage} from '~/utils/roles';
definePageMeta({layout:'default'});
const auth=useAuthStore(),store=useTutorInsightsStore(),ready=ref(false);
onMounted(async()=>{auth.initializeAuth();if(!auth.token)return navigateTo('/login');const user=await auth.fetchCurrentUser();if(Number(user?.role)!==3||!canAccessPage(user?.role,'student-insights'))return navigateTo('/dashboard');ready.value=true;await store.fetchSection('student-insights');});
</script>
<template><div v-if="ready" class="mx-auto w-full max-w-[1450px] min-w-0 px-4 py-5 sm:px-6 lg:px-8"><header class="mb-5 flex items-center justify-between gap-3"><div><h1 class="font-headline-md text-headline-md">Student Insights</h1><p class="text-sm text-on-surface-variant">Performa siswa secara agregat pada soal Tutor.</p></div><button class="text-primary-container" aria-label="Muat ulang" @click="store.fetchSection('student-insights')"><RefreshCw class="h-4 w-4"/></button></header><p v-if="store.error" role="alert" class="mb-4 rounded-2xl bg-danger-soft p-3 text-danger-rose">{{ store.error }}</p><div v-if="store.loading" class="h-48 animate-pulse rounded-3xl bg-surface-container"/><section v-else-if="!store.studentInsights?.available" class="rounded-3xl border border-soft-blue bg-surface-white p-8 text-center shadow-sm"><TrendingUp class="mx-auto mb-3 h-10 w-10 text-primary-container"/><h2 class="font-title-md text-title-md">Insights belum tersedia</h2><p class="mx-auto mt-2 max-w-xl text-sm text-on-surface-variant">{{ store.studentInsights?.notice || 'Data pengerjaan soal siswa belum tersedia.' }}</p></section><section v-else class="grid gap-4 sm:grid-cols-2"><article class="rounded-3xl border border-soft-blue bg-surface-white p-5 shadow-sm"><p class="text-sm text-on-surface-variant">Average Accuracy</p><strong class="font-title-md text-title-md">{{ store.studentInsights.average_accuracy??'—' }}</strong></article><article class="rounded-3xl border border-soft-blue bg-surface-white p-5 shadow-sm"><p class="text-sm text-on-surface-variant">Jumlah Pengerjaan</p><strong class="font-title-md text-title-md">{{ store.studentInsights.question_attempt_count??'—' }}</strong></article></section></div></template>
