<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { Users, ClipboardList, TrendingUp, Search, RefreshCw, ChevronLeft, ChevronRight, X, Target, Activity } from 'lucide-vue-next';
import { useAuthStore } from '~/stores/api/auth';
import { useAdminStudentProgressStore } from '~/stores/api/adminStudentProgress';
import { canAccessPage } from '~/utils/roles';

definePageMeta({ layout: 'default' });
const auth = useAuthStore();
const store = useAdminStudentProgressStore();
const ready = ref(false);
const campuses = ref([]);
const detailOpen = ref(false);
let searchTimer;
const card = 'min-w-0 rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-6';
const input = 'min-w-0 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5 font-body-sm text-body-sm text-on-surface outline-none focus:border-primary-container';
const metrics = computed(() => [
  { label: 'Total Siswa', value: store.summary?.total_students, icon: Users, tone: 'bg-pale-blue text-primary-container' },
  { label: 'Sudah Punya Rekap', value: store.summary?.students_with_recap, icon: ClipboardList, tone: 'bg-success-soft text-success-emerald' },
  { label: 'Belum Punya Rekap', value: store.summary?.students_without_recap, icon: Activity, tone: 'bg-soft-orange text-on-secondary-container' },
  { label: 'Rata-rata Skor Terakhir', value: score(store.summary?.average_latest_score), icon: TrendingUp, tone: 'bg-pale-blue text-primary-container' },
]);
function score(value) { return value == null ? '—' : Number(value).toLocaleString('id-ID', { maximumFractionDigits: 1 }); }
function date(value) { return value ? new Date(value).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'; }
function target(row) { return [row?.campus_short || row?.campus_name, row?.prodi_name].filter(Boolean).join(' · ') || 'Target kampus belum tersedia'; }
function change(row) { return row.score_change == null ? '—' : `${Number(row.score_change) > 0 ? '+' : ''}${score(row.score_change)}`; }
function changeTone(row) { return row.score_change == null ? 'text-outline' : Number(row.score_change) > 0 ? 'text-success-emerald' : Number(row.score_change) < 0 ? 'text-danger-rose' : 'text-on-surface-variant'; }
async function loadCampuses() { try { const result = await store.request('/kampus'); campuses.value = Array.isArray(result?.data) ? result.data : []; } catch { campuses.value = []; } }
function applyFilters() { store.pagination.page = 1; store.fetchStudents(); }
watch(() => store.filters.search, () => { clearTimeout(searchTimer); searchTimer = setTimeout(applyFilters, 350); });
watch(() => [store.filters.campus_id, store.filters.status, store.filters.sort], applyFilters);
onBeforeUnmount(() => clearTimeout(searchTimer));
async function changePage(page) { store.pagination.page = page; await store.fetchStudents(); }
async function openDetail(id) { detailOpen.value = true; await store.fetchDetail(id); }
onMounted(async () => {
  auth.initializeAuth();
  if (!auth.token) return navigateTo('/login');
  const user = await auth.fetchCurrentUser();
  if (Number(user?.role) !== 1 || !canAccessPage(user?.role, 'student-progress')) return navigateTo('/dashboard');
  ready.value = true;
  await Promise.all([store.fetchSummary().catch(() => { store.error = 'Gagal memuat ringkasan progress.'; }), store.fetchStudents(), loadCampuses()]);
});
</script>

<template>
  <div class="mx-auto w-full max-w-[1600px] min-w-0 px-4 py-5 sm:px-6 sm:py-7 lg:px-8">
    <template v-if="ready && Number(auth.user?.role) === 1">
      <header class="mb-5"><h1 class="font-headline-md text-headline-md text-on-surface">Progress Siswa</h1><p class="mt-1 font-body-sm text-body-sm text-on-surface-variant">Pantau target dan perkembangan skor tryout eksternal siswa.</p></header>
      <div v-if="store.error" role="alert" class="mb-5 flex items-center gap-3 rounded-2xl border border-soft-blue bg-surface-white p-4"><span class="flex-1">{{ store.error }}</span><button class="inline-flex items-center gap-2 text-primary-container" @click="store.fetchStudents(); store.fetchSummary()"><RefreshCw class="h-4 w-4" />Coba Lagi</button></div>
      <section class="mb-5 grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4" aria-label="Ringkasan progress siswa"><article v-for="metric in metrics" :key="metric.label" class="rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-5"><div class="mb-3 flex h-11 w-11 items-center justify-center rounded-2xl" :class="metric.tone"><component :is="metric.icon" class="h-[22px] w-[22px]" /></div><p class="font-caption text-caption text-outline">{{ metric.label }}</p><div v-if="!store.summary" class="mt-2 h-8 w-20 animate-pulse rounded-lg bg-surface-container" /><p v-else class="mt-1 font-headline-md text-headline-md text-on-surface">{{ metric.value ?? '—' }}</p></article></section>
      <section class="mb-5" :class="card"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label class="relative"><span class="sr-only">Cari siswa</span><Search class="pointer-events-none absolute left-3 top-3 h-4 w-4 text-outline" /><input v-model="store.filters.search" type="search" placeholder="Cari nama, email, sekolah..." :class="input" class="pl-9" /></label><label><span class="sr-only">Filter kampus target</span><select v-model="store.filters.campus_id" :class="input"><option value="">Semua Kampus Target</option><option v-for="campus in campuses" :key="campus.id" :value="campus.id">{{ campus.nama }}</option></select></label><label><span class="sr-only">Filter perkembangan</span><select v-model="store.filters.status" :class="input"><option value="">Semua Siswa</option><option value="with_recap">Sudah punya rekap</option><option value="without_recap">Belum punya rekap</option><option value="improving">Skor meningkat</option><option value="needs_attention">Skor menurun</option></select></label><label><span class="sr-only">Urutkan siswa</span><select v-model="store.filters.sort" :class="input"><option value="recent">Rekap terbaru</option><option value="name">Nama A–Z</option><option value="highest">Skor terbaik</option><option value="lowest">Skor terakhir terendah</option><option value="improvement">Peningkatan terbesar</option></select></label></div></section>
      <section :class="card"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-title-md text-title-md text-on-surface">Daftar Siswa</h2><p class="mt-1 font-caption text-caption text-outline">Skor dan perubahan dihitung dari rekap tryout yang dicatat siswa.</p></div><span class="font-caption text-caption text-outline">{{ store.pagination.total }} siswa</span></div>
        <div v-if="store.isLoading" class="space-y-3"><div v-for="i in 4" :key="i" class="h-16 animate-pulse rounded-2xl bg-surface-container" /></div>
        <div v-else-if="!store.students.length" class="py-10 text-center"><Users class="mx-auto mb-3 h-10 w-10 text-primary-container" /><p class="font-title-md text-title-md">Tidak ada siswa untuk filter ini.</p><p class="mt-1 text-on-surface-variant">Coba ubah pencarian atau filter.</p></div>
        <template v-else><div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[850px] text-left font-body-sm text-body-sm"><thead class="border-b border-soft-blue text-outline"><tr><th class="p-3">Siswa</th><th class="p-3">Target</th><th class="p-3">Rekap</th><th class="p-3">Skor Terbaik</th><th class="p-3">Skor Terakhir</th><th class="p-3">Perubahan</th><th class="p-3">Rekap Terakhir</th><th class="p-3">Detail</th></tr></thead><tbody><tr v-for="row in store.students" :key="row.user_id" class="border-b border-soft-blue"><td class="p-3"><span class="block font-label-sm text-label-sm text-on-surface">{{ row.nama }}</span><span class="block text-outline">{{ row.sekolah || row.email }}</span></td><td class="p-3">{{ target(row) }}</td><td class="p-3">{{ row.recap_count }}</td><td class="p-3">{{ score(row.best_score) }}</td><td class="p-3">{{ score(row.latest_score) }}</td><td class="p-3 font-label-sm text-label-sm" :class="changeTone(row)">{{ change(row) }}</td><td class="p-3">{{ date(row.last_recap_at) }}</td><td class="p-3"><button class="text-primary-container hover:underline" @click="openDetail(row.user_id)">Lihat</button></td></tr></tbody></table></div>
        <div class="space-y-3 md:hidden"><button v-for="row in store.students" :key="row.user_id" class="w-full rounded-2xl border border-soft-blue p-3 text-left" @click="openDetail(row.user_id)"><span class="flex justify-between gap-3"><strong class="truncate">{{ row.nama }}</strong><strong class="text-primary-container">{{ score(row.latest_score) }}</strong></span><span class="mt-1 block truncate text-on-surface-variant">{{ target(row) }}</span><span class="mt-1 flex justify-between gap-2 text-outline"><span>{{ row.recap_count }} rekap · {{ date(row.last_recap_at) }}</span><span :class="changeTone(row)">{{ change(row) }}</span></span></button></div></template>
        <div class="mt-4 flex items-center justify-end gap-3 font-body-sm text-body-sm"><span>Halaman {{ store.pagination.page }} / {{ store.pagination.total_pages }}</span><button :disabled="store.pagination.page <= 1" aria-label="Halaman sebelumnya" class="rounded-xl border border-soft-blue p-2 disabled:opacity-40" @click="changePage(store.pagination.page - 1)"><ChevronLeft class="h-4 w-4" /></button><button :disabled="store.pagination.page >= store.pagination.total_pages" aria-label="Halaman berikutnya" class="rounded-xl border border-soft-blue p-2 disabled:opacity-40" @click="changePage(store.pagination.page + 1)"><ChevronRight class="h-4 w-4" /></button></div>
      </section>
      <div v-if="detailOpen" class="fixed inset-0 z-50 flex justify-end bg-black/40" @click.self="detailOpen = false"><div role="dialog" aria-modal="true" aria-label="Detail progress siswa" class="h-full w-full max-w-xl overflow-y-auto bg-surface-white p-5 shadow-2xl sm:p-7"><div class="mb-5 flex items-start justify-between gap-3"><div><h2 class="font-title-md text-title-md">Detail Progress Siswa</h2><p class="font-caption text-caption text-outline">Berdasarkan hasil tryout eksternal yang tersimpan.</p></div><button aria-label="Tutup detail" @click="detailOpen = false"><X class="h-5 w-5" /></button></div><p v-if="store.isLoadingDetail">Memuat detail...</p><p v-else-if="store.detailError" role="alert">{{ store.detailError }}</p><template v-else-if="store.selectedStudent"><h3 class="font-title-md text-title-md">{{ store.selectedStudent.student.nama }}</h3><p class="text-on-surface-variant">{{ store.selectedStudent.student.sekolah || 'Sekolah belum diisi' }} · {{ store.selectedStudent.student.kelas || 'Kelas belum diisi' }}</p><p class="mb-5 text-on-surface-variant">{{ target(store.selectedStudent.student) }}</p><div class="mb-5 grid grid-cols-2 gap-3"><div v-for="entry in [['Target Skor',store.selectedStudent.student.target_score],['Skor Terakhir',store.selectedStudent.student.latest_score],['Skor Terbaik',store.selectedStudent.student.best_score],['Jumlah Rekap',store.selectedStudent.student.recap_count]]" :key="entry[0]" class="rounded-2xl border border-soft-blue p-3"><p class="text-outline">{{ entry[0] }}</p><strong>{{ score(entry[1]) }}</strong></div></div><p v-if="store.selectedStudent.student.target_gap != null" class="mb-5 flex items-center gap-2 rounded-2xl bg-pale-blue p-3 text-primary-container"><Target class="h-4 w-4" />Selisih dari target: {{ Number(store.selectedStudent.student.target_gap) > 0 ? '+' : '' }}{{ score(store.selectedStudent.student.target_gap) }} poin</p><h4 class="mb-2 font-label-sm text-label-sm">Tren Skor</h4><p v-if="!store.selectedStudent.trend.length" class="mb-5 text-on-surface-variant">Belum ada data skor.</p><div v-else class="mb-5 flex min-w-0 gap-2 overflow-x-auto pb-2"><div v-for="point in store.selectedStudent.trend" :key="point.recap_id" class="flex min-w-14 flex-col items-center justify-end gap-1"><span class="text-xs">{{ score(point.total_score) }}</span><div class="w-6 rounded-t bg-primary-container" :style="{ height: `${Math.max(4,Math.min(100,Number(point.total_score)/10))}px` }" /><span class="text-[10px] text-outline">{{ date(point.recap_at) }}</span></div></div><h4 class="mb-2 font-label-sm text-label-sm">Riwayat Rekap</h4><div v-for="row in store.selectedStudent.history" :key="row.recap_id" class="flex justify-between gap-3 border-t border-soft-blue py-3"><span>{{ row.platform || 'Platform tidak diketahui' }}<small class="block text-outline">{{ row.tryout_name || date(row.recap_at) }}</small></span><strong>{{ score(row.total_score) }}</strong></div></template></div></div>
    </template>
    <div v-else class="h-40 animate-pulse rounded-3xl bg-surface-container" aria-label="Memuat halaman" />
  </div>
</template>
