<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { BookOpen, BookOpenCheck, Search, ChevronRight, Play, CircleCheck, RefreshCw, Layers3 } from 'lucide-vue-next';
import { useUserMaterialsStore } from '~/stores/api/userMaterials';
const store = useUserMaterialsStore();
const search = ref(''), selectedSubtest = ref(''), selectedStatus = ref('all');
let timer;
const card = 'min-w-0 rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-6';
const label = status => ({ not_started: 'Belum Dimulai', in_progress: 'Sedang Dipelajari', completed: 'Selesai' })[status] || 'Belum Dimulai';
const action = status => status === 'completed' ? 'Review Materi' : status === 'in_progress' ? 'Lanjutkan' : 'Mulai Belajar';
const total = computed(() => store.summary?.total_materials || 0);
function searchLater() { clearTimeout(timer); timer = setTimeout(() => store.setSearch(search.value), 300); }
function chooseSubtest(code) { selectedSubtest.value = selectedSubtest.value === code ? '' : code; store.setSubtest(selectedSubtest.value); }
onMounted(() => store.fetchMaterials());
onBeforeUnmount(() => clearTimeout(timer));
</script>
<template>
  <div class="mx-auto w-full max-w-[1600px] min-w-0 px-4 py-5 text-on-surface sm:px-6 sm:py-7 lg:px-8"><header class="mb-5"><div class="inline-flex items-center gap-2 rounded-full bg-pale-blue px-3 py-1 text-xs font-semibold text-primary-container"><BookOpen class="h-4 w-4" /> Materi SNBT <span v-if="store.snbtYear">{{ store.snbtYear }}</span></div><h1 class="mt-3 text-2xl font-bold sm:text-3xl">Materi</h1><p class="mt-1 text-sm text-on-surface-variant">Pelajari materi SNBT berdasarkan subtes dan lanjutkan progres belajarmu.</p></header>
    <div v-if="store.error" role="alert" class="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-white p-4 text-sm text-rose-700"><span>{{ store.error }}</span><button class="inline-flex items-center gap-2 font-semibold" @click="store.fetchMaterials()"><RefreshCw class="h-4 w-4" /> Coba Lagi</button></div>
    <div v-if="store.isLoading && !store.summary" class="space-y-4" aria-label="Memuat materi"><div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="i in 4" :key="i" class="h-28 animate-pulse rounded-3xl bg-slate-200" /></div><div class="h-40 animate-pulse rounded-3xl bg-slate-200" /><div class="h-60 animate-pulse rounded-3xl bg-slate-200" /></div>
    <template v-else><section class="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><article v-for="item in [['Total Materi',total,BookOpen],['Materi Selesai',store.summary?.completed || 0,CircleCheck],['Sedang Dipelajari',store.summary?.in_progress || 0,Play],['Progress Keseluruhan',`${store.summary?.overall_progress || 0}%`,BookOpenCheck]]" :key="item[0]" :class="card"><component :is="item[2]" class="mb-3 h-5 w-5 text-primary-container" /><p class="text-xs text-outline">{{ item[0] }}</p><strong class="mt-1 block text-xl">{{ item[1] }}</strong></article></section>
      <section :class="card" class="mb-5"><div class="mb-4 flex items-center gap-2"><Layers3 class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Pilih Subtes</h2></div><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><button v-for="row in store.subtests" :key="row.code" class="min-w-0 rounded-2xl border p-3 text-left" :class="selectedSubtest === row.code ? 'border-blue-600 bg-pale-blue' : 'border-soft-blue hover:bg-surface-container-low'" @click="chooseSubtest(row.code)"><strong class="text-primary-container">{{ row.code }}</strong><span class="mt-1 block min-h-10 text-xs font-semibold leading-snug">{{ row.name }}</span><span class="mt-2 block text-xs text-outline">{{ row.total_materials }} materi · {{ row.completed }} selesai</span><span class="block text-xs text-outline">{{ row.progress }}%</span><div class="mt-2 h-1.5 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${row.progress}%` }" /></div></button></div></section>
      <div v-if="total" class="mb-5 grid gap-4 lg:grid-cols-2"><section :class="card"><h2 class="mb-3 font-bold">Lanjutkan Belajar</h2><template v-if="store.continueLearning"><p class="text-xs font-semibold text-primary-container">{{ store.continueLearning.subtest }}</p><h3 class="mt-1 font-semibold">{{ store.continueLearning.title }}</h3><p class="mt-2 line-clamp-2 text-sm text-on-surface-variant">{{ store.continueLearning.description || 'Buka dokumen untuk mempelajari materi ini.' }}</p><div class="mt-4 h-2 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${store.continueLearning.progress}%` }" /></div><p class="mt-1 text-xs text-outline">Progress {{ store.continueLearning.progress }}%</p><NuxtLink :to="`/materials/${store.continueLearning.material_id}`" class="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary-container">{{ action(store.continueLearning.status) }} <ChevronRight class="h-4 w-4" /></NuxtLink></template></section><section :class="card"><h2 class="mb-3 font-bold">Direkomendasikan Untukmu</h2><p v-if="!store.recommended.length" class="text-sm text-outline">Semua materi pada subtes prioritas sudah selesai, atau belum ada rekomendasi.</p><NuxtLink v-for="row in store.recommended" :key="row.material_id" :to="`/materials/${row.material_id}`" class="block border-b border-soft-blue py-2 last:border-0"><strong class="text-sm">{{ row.subtest }} · {{ row.title }}</strong><span class="block text-xs text-outline">{{ row.reason }}</span></NuxtLink></section></div>
      <section :class="card" class="mb-5"><div class="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 class="font-bold">Daftar Materi</h2><div class="flex flex-wrap gap-2"><label class="relative"><Search class="absolute left-3 top-2.5 h-4 w-4 text-outline" /><input v-model="search" type="search" placeholder="Cari materi..." class="w-44 rounded-xl border border-soft-blue bg-surface-container-low py-2 pl-9 pr-3 text-sm outline-none focus:border-primary-container sm:w-56" @input="searchLater" /></label><select v-model="selectedStatus" class="rounded-xl border border-soft-blue bg-surface-container-low px-3 py-2 text-sm" aria-label="Filter status" @change="store.setStatus(selectedStatus)"><option value="all">Semua Status</option><option value="not_started">Belum Dimulai</option><option value="in_progress">Sedang Dipelajari</option><option value="completed">Selesai</option></select></div></div><div v-if="store.isLoading" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><div v-for="i in 3" :key="i" class="h-40 animate-pulse rounded-2xl bg-slate-200" /></div><div v-else-if="store.materials.length" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><article v-for="row in store.materials" :key="row.material_id" class="min-w-0 rounded-2xl border border-soft-blue p-4"><div class="flex justify-between gap-2"><span class="rounded-full bg-pale-blue px-2 py-1 text-xs font-semibold text-primary-container">{{ row.subtest }}</span><span class="text-xs text-outline">{{ label(row.status) }}</span></div><h3 class="mt-3 font-semibold">{{ row.title }}</h3><p class="mt-1 line-clamp-2 min-h-10 text-xs text-on-surface-variant">{{ row.description || 'Dokumen materi SNBT tersedia untuk dibaca.' }}</p><div class="mt-3 flex justify-between text-xs text-outline"><span>1 dokumen · {{ row.practice_question_count }} soal latihan</span><strong>{{ row.progress }}%</strong></div><div class="mt-1 h-2 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${row.progress}%` }" /></div><NuxtLink :to="`/materials/${row.material_id}`" class="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary-container">{{ action(row.status) }} <ChevronRight class="h-4 w-4" /></NuxtLink></article></div><p v-else class="py-10 text-center text-sm text-outline">{{ total ? (search ? 'Materi tidak ditemukan.' : 'Belum ada materi tersedia untuk filter ini.') : 'Belum ada materi aktif tersedia.' }}</p><div v-if="store.pagination.total_pages > 1" class="mt-4 flex items-center justify-end gap-3 text-sm"><button :disabled="store.pagination.page <= 1" @click="store.fetchMaterials(store.pagination.page - 1)">Sebelumnya</button><span>{{ store.pagination.page }} / {{ store.pagination.total_pages }}</span><button :disabled="store.pagination.page >= store.pagination.total_pages" @click="store.fetchMaterials(store.pagination.page + 1)">Berikutnya</button></div></section>
      <section v-if="store.completedMaterials.length" :class="card"><h2 class="mb-3 font-bold">Materi Selesai</h2><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><NuxtLink v-for="row in store.completedMaterials" :key="row.material_id" :to="`/materials/${row.material_id}`" class="flex items-center justify-between rounded-xl bg-surface-container-low p-3 text-sm"><span class="min-w-0 truncate">{{ row.subtest }} · {{ row.title }}</span><CircleCheck class="h-4 w-4 shrink-0 text-primary-container" /></NuxtLink></div></section><p v-else-if="total" class="text-center text-xs text-outline">Belum ada materi yang selesai.</p>
    </template>
  </div>
</template>
