<script setup>
import { computed, onMounted, ref } from 'vue';
import { Route, Hourglass, GraduationCap, Star, CheckCircle2, Lock, BookOpen, CalendarDays, Lightbulb, Flag, ChartNoAxesCombined, ChevronRight, Target, TrendingUp, RefreshCw, Circle } from 'lucide-vue-next';
import { useAuthStore } from '~/stores/api/auth';
import { useUserRoadmapStore } from '~/stores/api/userRoadmap';
import { canAccessPage } from '~/utils/roles';

definePageMeta({ layout: 'default' });
const auth = useAuthStore();
const store = useUserRoadmapStore();
const ready = ref(false);
const selectedStage = ref(null);
const card = 'min-w-0 rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-6';
const stageDetail = computed(() => store.stages.find(stage => stage.id === selectedStage.value) || store.roadmap?.active_stage);
const firstName = computed(() => (store.roadmap?.user?.nama || auth.user?.nama || 'Teman').trim().split(/\s+/)[0]);
const score = value => value == null ? '—' : Number(value).toLocaleString('id-ID', { maximumFractionDigits: 1 });
const strength = value => ({ strong: 'Kuat', stable: 'Stabil', needs_attention: 'Perlu Perhatian', priority: 'Prioritas', no_data: 'Belum ada data' })[value] || 'Belum ada data';
const status = value => ({ completed: 'Selesai', active: 'Aktif', available: 'Terbuka', locked: 'Terkunci' })[value] || value;
const stageIcon = value => value === 'completed' ? CheckCircle2 : value === 'locked' ? Lock : Circle;
const gapText = computed(() => {
  const gap = store.tryout?.gap_to_target;
  return gap == null ? 'Belum dapat dihitung' : gap >= 0 ? 'Target tercapai 🎉' : `${score(Math.abs(gap))} poin lagi`;
});
const examText = computed(() => {
  const remaining = store.countdown?.days_remaining;
  return remaining == null ? 'Tanggal ujian belum ditetapkan' : remaining < 0 ? 'Periode SNBT telah selesai' : remaining === 0 ? 'Hari ini' : `${remaining} hari lagi`;
});

onMounted(async () => {
  auth.initializeAuth();
  if (!auth.token) return navigateTo('/login');
  const user = await auth.fetchCurrentUser();
  if (Number(user?.role) !== 2 || !canAccessPage(user?.role, 'roadmap.self')) return navigateTo('/dashboard');
  if (user?.is_activate !== true) return navigateTo('/dashboard');
  ready.value = true;
  await store.fetchRoadmap();
});
</script>

<template>
  <div class="mx-auto w-full max-w-[1600px] min-w-0 px-4 py-5 sm:px-6 sm:py-7 lg:px-8">
    <div v-if="!ready || store.isLoading" class="space-y-4" aria-label="Memuat roadmap">
      <div class="grid gap-4 lg:grid-cols-12"><div class="h-64 animate-pulse rounded-3xl bg-slate-200 lg:col-span-7" /><div class="h-64 animate-pulse rounded-3xl bg-slate-200 lg:col-span-5" /></div>
      <div class="h-44 animate-pulse rounded-3xl bg-slate-200" />
      <div class="grid gap-4 lg:grid-cols-12"><div class="h-96 animate-pulse rounded-3xl bg-slate-200 lg:col-span-8" /><div class="h-96 animate-pulse rounded-3xl bg-slate-200 lg:col-span-4" /></div>
    </div>
    <div v-else-if="store.error" role="alert" :class="card" class="flex flex-wrap items-center justify-between gap-3"><span>{{ store.error }}</span><button class="inline-flex items-center gap-2 rounded-xl bg-primary-container px-4 py-2 text-white" @click="store.fetchRoadmap()"><RefreshCw class="h-4 w-4" />Coba Lagi</button></div>
    <template v-else-if="store.roadmap">
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-12">
        <section class="relative min-w-0 overflow-hidden rounded-3xl bg-gradient-to-br from-blue-700 via-blue-600 to-indigo-700 p-5 text-white sm:p-7 lg:col-span-7">
          <div class="relative z-10"><span class="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold"><Route class="h-4 w-4" />Peta Persiapan SNBT {{ store.roadmap.snbt_year }}</span><h1 class="mt-5 max-w-xl text-2xl font-bold leading-tight sm:text-3xl">Roadmap Belajar Menuju Kampus Impian</h1><p class="mt-3 max-w-xl text-sm text-blue-100">Pantau progresmu dari penguasaan konsep dasar hingga evaluasi hasil tryout menjelang SNBT {{ store.roadmap.snbt_year }}.</p><p class="mt-5 font-semibold">Terus jaga konsistensi belajarmu, {{ firstName }}! 🚀</p><div class="mt-5 flex flex-wrap gap-2 text-xs"><span class="rounded-full bg-white/15 px-3 py-2">Fase Aktif: Tahap {{ store.currentStage }}</span><span class="inline-flex items-center gap-1 rounded-full bg-white/15 px-3 py-2"><Hourglass class="h-3.5 w-3.5" />{{ examText }}</span></div></div>
          <img src="/mascot/belajar.svg" alt="Maskot MatrIQ belajar" class="pointer-events-none absolute -bottom-10 -right-8 w-44 opacity-25 sm:w-56" />
        </section>
        <section :class="card" class="lg:col-span-5"><div class="flex items-center gap-2 text-primary-container"><GraduationCap class="h-5 w-5" /><span class="text-sm font-semibold">Target Pilihan 1</span></div><template v-if="store.target?.campus || store.target?.program"><h2 class="mt-3 text-xl font-bold text-on-surface">{{ store.target.campus || 'Kampus belum tersedia' }}</h2><p class="text-sm text-on-surface-variant">{{ store.target.program || 'Prodi belum tersedia' }}</p><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-pale-blue p-3"><p class="text-xs text-outline">Target Score</p><strong class="text-xl text-primary-container">{{ score(store.target.target_score) }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Skor Terakhir</p><strong class="text-xl text-on-surface">{{ score(store.tryout?.latest_score) }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Perubahan</p><strong :class="store.tryout?.delta > 0 ? 'text-success-emerald' : 'text-on-surface'">{{ store.tryout?.delta == null ? '—' : `${store.tryout.delta > 0 ? '+' : ''}${score(store.tryout.delta)} pt` }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Selisih Target</p><strong class="text-on-surface">{{ gapText }}</strong></div></div></template><div v-else class="mt-5 rounded-2xl bg-surface-container-low p-4"><p class="font-semibold">Belum ada target kampus.</p><p class="mt-1 text-sm text-on-surface-variant">Lengkapi target untuk membuat roadmap personal.</p><NuxtLink to="/profile" class="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary-container">Atur Target <ChevronRight class="h-4 w-4" /></NuxtLink></div></section>
      </div>

      <section :class="card" class="mb-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-bold text-on-surface">Kesiapan Keseluruhan</h2><p class="text-xs text-outline">Materi 30% · Latihan 25% · Akurasi 20% · Rekap 15% · Konsistensi 10%</p></div><strong class="text-3xl text-primary-container">{{ store.readiness.percentage }}%</strong></div><div class="mt-4 h-3 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container transition-all duration-700 motion-reduce:transition-none" :style="{ width: `${store.readiness.percentage}%` }" /></div><p v-if="!store.roadmap.study_summary.total_questions" class="mt-3 text-sm text-on-surface-variant">Roadmap kamu masih di tahap awal. Mulai belajar untuk membuka analisis progres.</p></section>

      <section id="stages" :class="card" class="mb-5"><div class="mb-4 flex items-center gap-2"><Route class="h-5 w-5 text-primary-container" /><h2 class="text-lg font-bold">Tahapan Roadmap</h2></div><div class="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-5"><button v-for="stage in store.stages" :key="stage.id" type="button" class="min-w-0 rounded-2xl border p-4 text-left transition-colors" :class="stageDetail?.id === stage.id ? 'border-blue-500 bg-pale-blue' : 'border-soft-blue hover:bg-surface-container-low'" @click="selectedStage = stage.id"><div class="flex items-center justify-between gap-2"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-600 text-sm font-bold text-white">{{ stage.id }}</span><component :is="stageIcon(stage.status)" class="h-4 w-4 text-primary-container" /></div><h3 class="mt-3 min-h-12 text-sm font-bold leading-snug">{{ stage.title }}</h3><p class="mt-2 text-xs text-outline">{{ status(stage.status) }} · {{ stage.detail }}</p><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-blue-600 transition-all duration-700 motion-reduce:transition-none" :style="{ width: `${stage.progress}%` }" /></div><p class="mt-1 text-right text-xs font-semibold">{{ stage.progress }}%</p></button></div></section>

      <div class="grid min-w-0 items-start gap-4 lg:grid-cols-12">
        <div class="min-w-0 space-y-4 lg:col-span-8">
          <section :class="card"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wide text-primary-container">Rincian Tahap {{ stageDetail?.id }}</p><h2 class="mt-1 text-xl font-bold">{{ stageDetail?.title }}</h2><p class="mt-1 text-sm text-on-surface-variant">{{ stageDetail?.description }}</p></div><span class="rounded-full bg-pale-blue px-3 py-1 text-sm font-semibold text-primary-container">{{ stageDetail?.progress }}%</span></div><div class="mt-5 h-2 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-blue-600 transition-all duration-700 motion-reduce:transition-none" :style="{ width: `${stageDetail?.progress || 0}%` }" /></div><div class="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-outline">Materi Selesai</p><strong>{{ store.roadmap.study_summary.completed_materials }} / {{ store.roadmap.study_summary.total_materials }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-outline">Soal Dikerjakan</p><strong>{{ store.roadmap.study_summary.total_questions }}</strong></div><div id="tryout" class="rounded-2xl bg-surface-container-low p-3"><p class="text-outline">Rekap Tryout Eksternal</p><strong>{{ store.tryout.total_recap }}</strong></div></div><p v-if="!store.tryout.total_recap" class="mt-4 text-sm text-on-surface-variant">Belum ada rekap tryout. Catat hasil tryout eksternal untuk mulai mengevaluasi perkembangan skor.</p></section>

          <section id="subtests" :class="card"><div class="mb-4 flex items-center gap-2"><BookOpen class="h-5 w-5 text-primary-container" /><div><h2 class="text-lg font-bold">Progres 7 Subtes</h2><p class="text-xs text-outline">Berdasarkan materi aktif dan latihan yang tercatat.</p></div></div><div class="space-y-3"><article v-for="subtest in store.subtests" :key="subtest.code" class="rounded-2xl border border-soft-blue p-3 sm:p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-bold text-primary-container">{{ subtest.code }}</p><h3 class="font-semibold">{{ subtest.name }}</h3><p class="mt-1 text-xs text-outline">{{ subtest.topics_completed }} / {{ subtest.topics_total }} modul · {{ subtest.questions_attempted }} soal · Akurasi {{ subtest.accuracy == null ? '—' : `${subtest.accuracy}%` }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="subtest.strength === 'strong' ? 'bg-success-soft text-success-emerald' : subtest.strength === 'priority' ? 'bg-soft-orange text-on-secondary-container' : 'bg-pale-blue text-primary-container'">{{ strength(subtest.strength) }}</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-surface-container"><div class="h-full rounded-full bg-blue-600 transition-all duration-700 motion-reduce:transition-none" :style="{ width: `${subtest.progress}%` }" /></div><p class="mt-2 text-xs text-on-surface-variant">{{ subtest.recommended_action }}</p></article></div></section>

          <section :class="card"><div class="flex items-center gap-2"><Target class="h-5 w-5 text-primary-container" /><h2 class="text-lg font-bold">Rekomendasi Belajar Hari Ini</h2></div><h3 class="mt-4 font-bold">{{ store.recommendation?.title }}</h3><p class="mt-1 text-sm text-on-surface-variant">{{ store.recommendation?.description }}</p><p v-if="store.recommendation?.estimated_minutes" class="mt-3 text-xs text-outline">Estimasi berdasarkan rata-rata sesi belajarmu: {{ store.recommendation.estimated_minutes }} menit</p><p v-if="store.recommendation?.reason" class="mt-2 text-xs font-semibold text-primary-container">{{ store.recommendation.reason }}</p><NuxtLink v-if="store.recommendation?.subtest_code" to="/study-plan?source=roadmap" class="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary-container">Jadwalkan di Study Plan <ChevronRight class="h-4 w-4" /></NuxtLink></section>
        </div>

        <aside class="min-w-0 space-y-4 lg:col-span-4"><section :class="card" class="relative overflow-hidden bg-pale-blue"><div class="flex items-center gap-2 text-primary-container"><Lightbulb class="h-5 w-5" /><h2 class="font-bold">Tips MatrIQ Hari Ini</h2></div><p class="relative z-10 mt-3 max-w-[75%] text-sm text-on-surface-variant">{{ store.tip?.content }}</p><img src="/mascot/duduk-nobg.svg" alt="Maskot MatrIQ" class="absolute -bottom-3 -right-4 w-24 opacity-80 sm:w-28" /></section>
          <section :class="card"><div class="mb-3 flex items-center gap-2"><Flag class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Milestone Terdekat</h2></div><p v-if="!store.milestones.length" class="text-sm text-on-surface-variant">Semua target roadmap yang tersedia sudah tercapai.</p><div v-for="milestone in store.milestones" :key="`${milestone.type}-${milestone.title}`" class="border-t border-soft-blue py-3 first:border-t-0"><component :is="milestone.path ? 'a' : 'div'" :href="milestone.path || undefined" class="flex items-start justify-between gap-2 text-sm"><span class="font-semibold">{{ milestone.title }}</span><ChevronRight v-if="milestone.path" class="h-4 w-4 shrink-0 text-primary-container" /></component><p v-if="milestone.due_at" class="mt-1 text-xs text-outline">{{ new Date(`${milestone.due_at}T00:00:00`).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) }}</p><div v-if="milestone.progress > 0" class="mt-2 h-1.5 rounded-full bg-surface-container"><div class="h-full rounded-full bg-blue-600" :style="{ width: `${milestone.progress}%` }" /></div></div></section>
          <section :class="card"><div class="mb-3 flex items-center gap-2"><ChartNoAxesCombined class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Performa Subtes</h2></div><p class="mb-3 text-xs text-outline">Skor rekap terbaru jika ada; selebihnya akurasi latihan.</p><div v-for="item in store.performance" :key="item.code" class="flex items-center justify-between gap-2 border-t border-soft-blue py-2.5 text-sm"><span class="min-w-0 truncate">{{ item.code }} <small class="block truncate text-xs text-outline">{{ item.source === 'tryout_score' ? 'Skor tryout' : item.source === 'practice_accuracy' ? 'Akurasi latihan' : 'Belum ada data' }}</small></span><strong>{{ score(item.value) }}{{ item.source === 'practice_accuracy' ? '%' : '' }}</strong></div><div v-if="store.roadmap.average_subtest_score != null" class="mt-3 flex justify-between rounded-2xl bg-pale-blue p-3 text-sm"><span>Rata-rata Skor Saat Ini</span><strong class="text-primary-container">{{ score(store.roadmap.average_subtest_score) }}</strong></div></section>
          <section :class="card"><div class="flex items-center gap-2"><CalendarDays class="h-5 w-5 text-primary-container" /><h2 class="font-bold">Hitung Mundur SNBT</h2></div><p class="mt-3 text-lg font-bold text-primary-container">{{ examText }}</p><p v-if="store.countdown?.exam_date" class="text-sm text-outline">{{ new Date(`${store.countdown.exam_date}T00:00:00`).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) }}</p></section></aside>
      </div>
    </template>
  </div>
</template>
