<script setup>
import { computed, onMounted, ref } from 'vue';
import { Activity, Target, Trophy, Brain, BookOpenCheck, Clock3, Flame, CalendarCheck2, ChartNoAxesCombined, Sparkles, RefreshCw, Lightbulb } from 'lucide-vue-next';
import { useUserAnalyticsStore } from '~/stores/api/userAnalytics';
import Panel from '~/components/analytics/Panel.vue';
import LineChart from '~/components/analytics/LineChart.vue';
import BarChart from '~/components/analytics/BarChart.vue';
import UserTryoutTrend from '~/components/analytics/UserTryoutTrend.vue';
const store = useUserAnalyticsStore();
const activityMode = ref('questions'), tryoutMode = ref('latest'), showAllMaterials = ref(false);
const number = value => value == null ? '—' : Number(value).toLocaleString('id-ID', { maximumFractionDigits: 1 });
const percent = value => value == null ? '—' : `${number(value)}%`;
const duration = minutes => minutes == null ? '—' : `${Math.floor(Number(minutes) / 60)}j ${Number(minutes) % 60}m`;
const date = value => value ? new Date(`${value}T00:00:00Z`).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }) : '—';
const note = value => value == null ? '—' : `${value > 0 ? '+' : ''}${number(value)}`;
const cards = computed(() => [
  { label: 'Total Soal', value: number(store.overview?.questions_attempted), note: `${note(store.overview?.questions_delta)} vs periode sebelumnya`, icon: BookOpenCheck },
  { label: 'Akurasi', value: percent(store.overview?.accuracy), note: `${note(store.overview?.accuracy_delta)} poin persentase`, icon: Target },
  { label: 'Waktu Belajar', value: duration(store.overview?.study_minutes), note: `${note(store.overview?.study_minutes_delta)} menit`, icon: Clock3 },
  { label: 'Study Streak', value: `${number(store.overview?.streak_days || 0)} hari`, note: 'Hari belajar berturut-turut', icon: Flame },
  { label: 'Skor Tryout Terakhir', value: number(store.overview?.latest_tryout_score), note: `${note(store.overview?.latest_tryout_delta)} poin`, icon: Trophy },
  { label: 'Target Score', value: number(store.overview?.target_score), note: store.target?.gap == null ? 'Atur target untuk melihat selisih' : store.target.gap ? `${number(store.target.gap)} poin dari best score` : 'Target tercapai', icon: ChartNoAxesCombined },
]);
const subtestBars = computed(() => store.subtests.map(row => ({ label: row.code, total: row.accuracy || 0, questions: row.questions_attempted, status: row.status })));
const levelBars = computed(() => store.difficultyLevels.map(row => ({ label: row.name, total: row.accuracy || 0, questions: row.questions_attempted, status: row.status })));
const tryoutSubtests = computed(() => store.tryout?.subtests?.map(row => ({ label: row.code, total: tryoutMode.value === 'latest' ? row.latest : row.average })) || []);
const visibleMaterials = computed(() => showAllMaterials.value ? store.materials : store.materials.slice(0, 6));
const heatMax = computed(() => Math.max(1, ...store.studyConsistency.map(row => row.study_minutes || row.questions)));
const heatColor = row => { const value = row.study_minutes || row.questions; return value ? `rgba(37,99,235,${.18 + .82 * value / heatMax.value})` : '#e2e8f0'; };
const hasData = computed(() => Boolean(store.practice?.questions_attempted || store.tryout?.trend?.length || store.studyPlan?.planned || store.studyTime?.total_minutes));
const card = 'min-w-0 rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm';
onMounted(() => store.fetchAnalytics());
</script>
<template>
  <div class="mx-auto w-full max-w-[1700px] min-w-0 px-4 py-5 text-on-surface sm:px-6 sm:py-7 lg:px-8"><header class="mb-5 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-bold sm:text-3xl">Analytics</h1><p class="mt-1 max-w-2xl text-sm text-on-surface-variant">Pantau perkembangan belajar, performa latihan, dan progresmu menuju target SNBT.</p></div><span v-if="store.analytics?.snbt_year" class="rounded-full bg-pale-blue px-3 py-1.5 text-xs font-semibold text-primary-container">SNBT {{ store.analytics.snbt_year }}</span></header>
    <section :class="card" class="mb-5"><div class="flex flex-wrap items-center gap-2"><button v-for="option in [['7d','7 Hari'],['30d','30 Hari'],['3m','3 Bulan'],['6m','6 Bulan'],['all','Semua']]" :key="option[0]" class="rounded-xl px-3 py-2 text-sm font-semibold" :class="store.range === option[0] && !store.dateFrom ? 'bg-primary-container text-white' : 'bg-surface-container-low text-on-surface-variant'" @click="store.setRange(option[0])">{{ option[1] }}</button></div><div class="mt-3 flex flex-wrap items-end gap-2 text-xs"><label>Dari<input v-model="store.dateFrom" type="date" class="mt-1 block rounded-xl border border-soft-blue px-3 py-2" /></label><label>Sampai<input v-model="store.dateTo" type="date" class="mt-1 block rounded-xl border border-soft-blue px-3 py-2" /></label><button :disabled="!store.dateFrom || !store.dateTo" class="rounded-xl border border-primary-container px-3 py-2 text-primary-container disabled:opacity-40" @click="store.fetchAnalytics()">Terapkan</button><span v-if="store.analytics?.period" class="ml-auto text-outline">{{ store.analytics.period.from ? `${date(store.analytics.period.from)} – ` : 'Sejak awal – ' }}{{ date(store.analytics.period.to) }}</span></div></section>
    <div v-if="store.error" role="alert" class="mb-5 flex items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-white p-4 text-sm text-rose-700"><span>{{ store.error }}</span><button class="inline-flex items-center gap-2 font-semibold" @click="store.refreshAnalytics()"><RefreshCw class="h-4 w-4" />Coba Lagi</button></div>
    <div v-if="store.isLoading && !store.analytics" class="space-y-4" aria-label="Memuat Analytics"><div class="grid grid-cols-2 gap-3 lg:grid-cols-3 2xl:grid-cols-6"><div v-for="i in 6" :key="i" class="h-28 animate-pulse rounded-3xl bg-slate-200" /></div><div v-for="i in 3" :key="i" class="h-56 animate-pulse rounded-3xl bg-slate-200" /></div>
    <template v-else-if="store.analytics"><section class="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-3 2xl:grid-cols-6"><article v-for="metric in cards" :key="metric.label" :class="card"><component :is="metric.icon" class="mb-3 h-5 w-5 text-primary-container" /><p class="text-xs text-outline">{{ metric.label }}</p><strong class="mt-1 block text-lg">{{ metric.value }}</strong><p class="mt-2 text-xs text-on-surface-variant">{{ metric.note }}</p></article></section>
      <section v-if="!hasData" :class="card" class="mb-5 text-center"><Brain class="mx-auto h-9 w-9 text-primary-container" /><h2 class="mt-3 text-lg font-bold">Belum cukup data untuk Analytics</h2><p class="mt-1 text-sm text-on-surface-variant">Mulai belajar, kerjakan Practice, dan tambahkan rekap tryout untuk melihat perkembanganmu di sini.</p><div class="mt-4 flex justify-center gap-3"><NuxtLink to="/practice" class="rounded-xl bg-primary-container px-4 py-2 text-sm font-semibold text-white">Mulai Practice</NuxtLink><NuxtLink to="/study-plan" class="rounded-xl border border-soft-blue px-4 py-2 text-sm font-semibold">Buat Study Plan</NuxtLink></div></section>
      <Panel title="Aktivitas Belajar" subtitle="Jumlah soal yang dijawab dan menit belajar per hari" :loading="store.isLoading" class="mb-5"><div class="mb-3 flex gap-2 text-xs"><button class="rounded-xl px-3 py-1.5" :class="activityMode === 'questions' ? 'bg-primary-container text-white' : 'bg-surface-container-low'" @click="activityMode = 'questions'">Soal</button><button class="rounded-xl px-3 py-1.5" :class="activityMode === 'study_minutes' ? 'bg-primary-container text-white' : 'bg-surface-container-low'" @click="activityMode = 'study_minutes'">Waktu Belajar</button></div><LineChart :rows="store.activityTrend" :series="[{ key: activityMode, label: activityMode === 'questions' ? 'Soal' : 'Menit belajar' }]" area /></Panel>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Performa Practice" subtitle="Hanya sesi selesai; akurasi dari jawaban yang diberikan" :loading="store.isLoading"><div class="mb-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-3"><div v-for="item in [['Sesi',store.practice?.total_sessions],['Dijawab',store.practice?.questions_attempted],['Benar',store.practice?.correct],['Salah',store.practice?.wrong],['Akurasi',percent(store.practice?.accuracy)],['Durasi Rata-rata',store.practice?.average_session_seconds == null ? '—' : `${Math.round(store.practice.average_session_seconds / 60)} menit`]]" :key="item[0]" class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">{{ item[0] }}</p><strong>{{ item[1] ?? '—' }}</strong></div></div><LineChart :rows="store.practice?.trend || []" :series="[{ key:'accuracy',label:'Akurasi %' }]" /></Panel><Panel title="Performa Subtes" subtitle="Akurasi Practice; urut dari tertinggi" :loading="store.isLoading"><BarChart :rows="subtestBars" :max="100" /><div class="mt-3 space-y-1 text-xs text-outline"><p v-for="row in store.subtests" :key="row.code">{{ row.code }} · {{ row.questions_attempted }} soal · {{ row.status }}</p></div></Panel></div>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Performa Berdasarkan Level" subtitle="Minimal 10 jawaban untuk menyimpulkan status" :loading="store.isLoading"><BarChart :rows="levelBars" :max="100" /><div class="mt-3 grid grid-cols-2 gap-2 text-xs"><div v-for="row in store.difficultyLevels" :key="row.level" class="rounded-xl bg-surface-container-low p-2"><strong>{{ row.name }}</strong><p>{{ row.questions_attempted }} soal · {{ row.status }}</p></div></div></Panel><Panel title="Perkembangan Skor Tryout" subtitle="Hasil platform eksternal pada periode terpilih" :loading="store.isLoading"><UserTryoutTrend :rows="store.tryout?.trend || []" :target="store.tryout?.target" /><NuxtLink to="/tryout-recap" class="mt-3 inline-block text-sm font-semibold text-primary-container">Lihat Rekap Tryout</NuxtLink></Panel></div>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Progress Menuju Target" subtitle="Kesiapan terhadap Target; memakai best score sepanjang masa" :loading="store.isLoading"><template v-if="store.target?.target_score"><p class="font-semibold">{{ store.target.campus || 'Kampus belum dipilih' }} · {{ store.target.program || 'Program belum dipilih' }}</p><div class="mt-4 grid grid-cols-3 gap-2 text-sm"><div><p class="text-xs text-outline">Target</p><strong>{{ number(store.target.target_score) }}</strong></div><div><p class="text-xs text-outline">Best Score</p><strong>{{ number(store.target.best_score) }}</strong></div><div><p class="text-xs text-outline">Selisih</p><strong>{{ store.target.gap == null ? '—' : `${number(store.target.gap)} poin` }}</strong></div></div><div class="mt-4 h-3 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container transition-all motion-reduce:transition-none" :style="{ width: `${store.target.progress || 0}%` }" /></div><p class="mt-2 text-sm text-primary-container">{{ store.target.status || 'Tambahkan rekap untuk melihat progres' }}</p></template><div v-else><p class="text-sm text-on-surface-variant">Belum ada target PTN. Analytics lainnya tetap bisa digunakan.</p><NuxtLink to="/profile" class="mt-3 inline-block text-sm font-semibold text-primary-container">Atur Target</NuxtLink></div></Panel><Panel title="Konsistensi Belajar" subtitle="Aktivitas harian; warna lebih kuat berarti lebih banyak menit belajar" :loading="store.isLoading"><div class="grid grid-cols-12 gap-1"><div v-for="row in store.studyConsistency" :key="row.day" class="aspect-square min-w-0 rounded-[4px]" :style="{ backgroundColor: heatColor(row) }" :title="`${date(row.day)} · ${row.study_minutes} menit · ${row.questions} soal`" /></div><p class="mt-3 text-xs text-outline">{{ store.studyConsistency.length }} hari terakhir pada periode · streak {{ store.overview?.streak_days || 0 }} hari</p></Panel></div>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Efektivitas Study Plan" subtitle="Rencana pada periode terpilih" :loading="store.isLoading"><div class="grid grid-cols-4 gap-2 text-sm"><div v-for="item in [['Rencana',store.studyPlan?.planned],['Selesai',store.studyPlan?.completed],['Terlewat',store.studyPlan?.missed],['Completion',percent(store.studyPlan?.completion_rate)]]" :key="item[0]" class="rounded-xl bg-surface-container-low p-2"><p class="text-xs text-outline">{{ item[0] }}</p><strong>{{ item[1] ?? '—' }}</strong></div></div><div class="mt-4 h-3 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary-container" :style="{ width: `${store.studyPlan?.completion_rate || 0}%` }" /></div><LineChart class="mt-4" :rows="store.studyPlan?.weekly_trend || []" :series="[{ key:'completion_rate',label:'Completion %' }]" /></Panel><Panel title="Waktu Belajar" subtitle="Berdasarkan waktu belajar yang tercatat" :loading="store.isLoading"><div class="grid grid-cols-2 gap-3 text-sm"><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Total</p><strong>{{ duration(store.studyTime?.total_minutes) }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3"><p class="text-xs text-outline">Rata-rata / hari aktif</p><strong>{{ duration(store.studyTime?.average_active_day_minutes) }}</strong></div><div class="rounded-2xl bg-surface-container-low p-3 sm:col-span-2"><p class="text-xs text-outline">Tanggal Paling Aktif</p><strong>{{ store.studyTime?.most_active_date ? `${store.studyTime.most_active_day}, ${date(store.studyTime.most_active_date)}` : '—' }}</strong></div></div></Panel></div>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Subtes Tryout" subtitle="Skor eksternal; tidak disamakan dengan akurasi Practice" :loading="store.isLoading"><div class="mb-3 flex gap-2 text-xs"><button class="rounded-xl px-3 py-1.5" :class="tryoutMode === 'latest' ? 'bg-primary-container text-white' : 'bg-surface-container-low'" @click="tryoutMode = 'latest'">Tryout Terakhir</button><button class="rounded-xl px-3 py-1.5" :class="tryoutMode === 'average' ? 'bg-primary-container text-white' : 'bg-surface-container-low'" @click="tryoutMode = 'average'">Rata-rata</button></div><BarChart :rows="tryoutSubtests" :max="1000" /></Panel><Panel title="Practice vs Tryout" subtitle="Dua metrik deskriptif dari sumber berbeda" :loading="store.isLoading"><div class="space-y-2"><div v-for="row in store.subtests" :key="row.code" class="grid grid-cols-[40px_1fr_1fr] gap-2 rounded-xl bg-surface-container-low p-2 text-sm"><strong>{{ row.code }}</strong><span>Practice {{ percent(row.accuracy) }}</span><span>Tryout {{ number(row.latest_tryout_score) }}</span></div></div></Panel></div>
      <Panel title="Performa Materi" subtitle="Berdasarkan jawaban pada sesi Practice yang selesai; akurasi rendah di atas" :loading="store.isLoading" class="mb-5"><div v-if="store.materials.length" class="overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><thead class="border-b border-soft-blue text-outline"><tr><th class="p-2">Materi</th><th class="p-2">Subtes</th><th class="p-2">Soal</th><th class="p-2">Akurasi</th><th class="p-2">Level</th><th class="p-2">Status</th></tr></thead><tbody><tr v-for="row in visibleMaterials" :key="row.material_id" class="border-b border-soft-blue"><td class="p-2 font-semibold">{{ row.title }}</td><td class="p-2">{{ row.subtest }}</td><td class="p-2">{{ number(row.questions_attempted) }}</td><td class="p-2">{{ percent(row.accuracy) }}</td><td class="p-2">{{ row.highest_level }}</td><td class="p-2">{{ row.status }}</td></tr></tbody></table></div><p v-else class="py-6 text-center text-sm text-outline">Belum ada materi dengan sesi Practice selesai.</p><button v-if="store.materials.length > 6" class="mt-3 text-sm font-semibold text-primary-container" @click="showAllMaterials = !showAllMaterials">{{ showAllMaterials ? 'Tampilkan Lebih Sedikit' : 'Lihat Semua Materi' }}</button></Panel>
      <div class="mb-5 grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Kekuatanmu" subtitle="Minimal 10 jawaban pada subtes" :loading="store.isLoading"><template v-if="store.strength"><p class="text-lg font-bold text-primary-container">{{ store.strength.name }}</p><p class="mt-2 text-sm">Akurasi Practice {{ percent(store.strength.accuracy) }} dari {{ store.strength.questions_attempted }} soal</p><p class="text-sm text-outline">Tryout terakhir {{ number(store.strength.latest_tryout_score) }}</p></template><p v-else class="text-sm text-outline">Data belum cukup untuk menyimpulkan kekuatan subtes.</p></Panel><Panel title="Prioritas Utama" subtitle="Akurasi terendah dengan sampel memadai" :loading="store.isLoading"><template v-if="store.weakness"><p class="text-lg font-bold text-primary-container">{{ store.weakness.name }}</p><p class="mt-2 text-sm">Akurasi Practice {{ percent(store.weakness.accuracy) }} dari {{ store.weakness.questions_attempted }} soal</p><p class="text-sm text-outline">Tryout terakhir {{ number(store.weakness.latest_tryout_score) }}</p></template><p v-else class="text-sm text-outline">Belum ada prioritas yang dapat disimpulkan dari data Practice.</p></Panel></div>
      <div class="grid min-w-0 gap-4 lg:grid-cols-2"><Panel title="Insight untuk Kamu" subtitle="Kesimpulan berbasis data yang tersedia" :loading="store.isLoading"><div v-if="store.insights.length" class="space-y-3"><p v-for="item in store.insights" :key="item" class="flex gap-2 rounded-xl bg-pale-blue p-3 text-sm"><Lightbulb class="h-4 w-4 shrink-0 text-primary-container" />{{ item }}</p></div><p v-else class="text-sm text-outline">Belum cukup data untuk insight pribadi.</p></Panel><Panel title="Fokus Berikutnya" subtitle="Langkah yang dapat dilakukan sekarang" :loading="store.isLoading"><div class="flex items-center gap-2"><Sparkles class="h-5 w-5 text-primary-container" /><h3 class="font-bold">{{ store.recommendedFocus?.name }}</h3></div><p class="mt-2 text-sm text-on-surface-variant">{{ store.recommendedFocus?.reason }}</p><p v-if="store.recommendedFocus?.material" class="mt-2 text-sm">Materi: {{ store.recommendedFocus.material }}</p><div class="mt-5 flex flex-wrap gap-2"><NuxtLink v-for="action in store.recommendedFocus?.actions || []" :key="action.path" :to="action.path" class="rounded-xl border border-primary-container px-3 py-2 text-xs font-semibold text-primary-container">{{ action.label }}</NuxtLink></div></Panel></div>
    </template>
  </div>
</template>

