<script setup>
import { computed, onMounted, ref } from 'vue';
import { Settings, Users, BookOpen, ShieldCheck, Server, Save, SlidersHorizontal, RefreshCw } from 'lucide-vue-next';
import { useAuthStore } from '~/stores/api/auth';
import { useAdminSettingsStore } from '~/stores/api/adminSettings';
import { canAccessPage } from '~/utils/roles';

definePageMeta({layout:'default'});
const auth=useAuthStore(), store=useAdminSettingsStore();
const ready=ref(false), tab=ref('general');
const sections=[{key:'general',label:'General',icon:Settings},{key:'users',label:'User & Roles',icon:Users},{key:'learning',label:'Learning',icon:BookOpen},{key:'content',label:'Content & Moderation',icon:SlidersHorizontal},{key:'security',label:'Security',icon:ShieldCheck},{key:'system',label:'System',icon:Server}];
const fields={
  general:[['app_name','App Name','Nama aplikasi yang ditampilkan kepada pengguna.','text'],['app_tagline','Tagline','Deskripsi singkat MatrIQ.','text'],['support_email','Support Email','Alamat bantuan pengguna.','email'],['support_contact','Support Contact','Kontak bantuan tambahan.','text'],['support_whatsapp','Support WhatsApp','Nomor internasional, contoh 628123456789.','text'],['support_instagram','Support Instagram','Username atau URL profil instagram.com.','text'],['active_snbt_year','Active SNBT Year','Tahun SNBT yang sedang berjalan.','number'],['timezone','Default Timezone','Zona waktu aplikasi.','select',['Asia/Jakarta']]],
  users:[['registration_enabled','Public Registration','Izinkan pendaftaran akun melalui halaman register.','boolean'],['default_user_role','Default User Role','Role akun baru dari registrasi publik.','select',[2,3]],['onboarding_required','Onboarding Required','Kewajiban onboarding untuk pengguna baru.','boolean'],['auto_activate_new_user','Auto Activate New User','Penanda onboarding selesai untuk akun baru.','boolean']],
  learning:[['default_daily_question_target','Default Daily Question Target','Target jumlah soal harian.','number'],['default_target_score','Default Target Score','Target skor awal.','number'],['min_target_score','Min Target Score','Batas bawah target skor.','number'],['max_target_score','Max Target Score','Batas atas target skor.','number'],['active_subtests','Active Subtests','Subtes yang tersedia untuk pembelajaran.','array',['PU','PPU','PBM','PK','LBI','LBE','PM']],['focus_accuracy_threshold','Focus Accuracy Threshold','Akurasi di bawah angka ini perlu perhatian.','number']],
  content:[['tutor_submission_requires_review','Tutor Submission Requires Review','Soal tutor harus masuk antrean moderasi.','boolean'],['admin_question_default_status','Admin Question Default Status','Status awal ketika admin membuat soal tanpa memilih status.','select',['draft','active']],['rejection_reason_required','Rejection Reason Required','Wajibkan alasan saat menolak soal.','boolean'],['allow_tutor_resubmit','Allow Tutor Resubmit','Izinkan tutor mengirim ulang soal yang ditolak.','boolean'],['tutor_can_edit_while_review','Tutor Can Edit While Review','Izinkan perubahan soal saat menunggu review.','boolean'],['question_difficulties','Allowed Question Difficulties','Pilihan tingkat kesulitan soal.','array',['easy','medium','hard']],['default_question_option_count','Default Question Options','Jumlah pilihan jawaban standar.','number']],
  security:[['minimum_password_length','Minimum Password Length','Panjang minimum password baru.','number'],['session_expiry_days','Session Expiry Days','Masa berlaku token login baru dalam hari.','number'],['max_login_attempts','Max Login Attempts','Batas percobaan login.','number'],['inactive_user_login_allowed','Inactive Users Can Login','Memerlukan status akun terpisah dari onboarding.','boolean']],
  system:[['maintenance_mode','Maintenance Mode','Batasi akses API pengguna non-admin sementara.','boolean'],['maintenance_message','Maintenance Message','Pesan yang tampil saat pemeliharaan.','textarea'],['default_export_format','Default Export Format','Format ekspor pilihan admin.','select',['csv','xlsx']],['export_row_limit','Export Row Limit','Batas maksimum baris untuk satu ekspor.','number'],['export_history_retention_days','Export History Retention Days','Usia riwayat ekspor yang disimpan.','number']],
};
const currentFields=computed(()=>fields[tab.value]||[]);
const input='min-w-0 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5 font-body-sm text-body-sm text-on-surface outline-none focus:border-primary-container';
const card='rounded-3xl border border-soft-blue bg-surface-white p-4 shadow-sm sm:p-5';
const statuses=computed(()=>[
  ['API',store.systemStatus?.api],['Database',store.systemStatus?.database],['Cloudinary',store.systemStatus?.cloudinary],['Environment',store.systemStatus?.environment],['App Version',store.systemStatus?.version],
]);
function toggleArray(key,value) { const list=store.settings[tab.value][key] || []; store.settings[tab.value][key]=list.includes(value)?list.filter(item=>item!==value):[...list,value]; }
onMounted(async()=>{ auth.initializeAuth(); if(!auth.token) return navigateTo('/login'); const user=await auth.fetchCurrentUser(); if(Number(user?.role)!==1 || !canAccessPage(user?.role,'settings.read')) return navigateTo('/dashboard'); ready.value=true; await Promise.all([store.fetchSettings(),store.fetchSystemStatus()]); });
</script>

<template>
  <div class="mx-auto w-full max-w-[1500px] min-w-0 px-4 py-5 sm:px-6 sm:py-7 lg:px-8">
    <template v-if="ready && Number(auth.user?.role)===1">
      <header class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 class="font-headline-md text-headline-md text-on-surface">Settings</h1><p class="mt-1 font-body-sm text-body-sm text-on-surface-variant">Kelola konfigurasi global MatrIQ.</p></div><button type="button" :disabled="!store.hasChanges||store.isSaving" class="inline-flex items-center gap-2 rounded-2xl bg-primary-container px-4 py-2.5 font-label-sm text-label-sm text-white disabled:opacity-50" @click="store.saveSettings()"><Save class="h-4 w-4"/>{{ store.isSaving?'Menyimpan...':'Simpan Perubahan' }}</button></header>
      <p v-if="store.error" role="alert" class="mb-4 rounded-2xl border border-danger-rose bg-surface-white p-3 text-sm text-danger-rose">{{ store.error }}</p><p v-if="store.success" role="status" class="mb-4 rounded-2xl bg-success-soft p-3 text-sm text-success-emerald">{{ store.success }}</p>
      <div v-if="store.hasChanges" class="mb-4 flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-soft-orange px-4 py-3 text-sm text-on-surface"><span>Perubahan belum disimpan.</span><button type="button" class="text-primary-container" @click="store.resetChanges()">Batalkan Perubahan</button></div>
      <div class="grid min-w-0 gap-5 lg:grid-cols-[200px_minmax(0,1fr)]"><nav aria-label="Kategori pengaturan" class="flex min-w-0 gap-2 overflow-x-auto lg:flex-col"><button v-for="section in sections" :key="section.key" type="button" :aria-current="tab===section.key?'page':undefined" class="inline-flex shrink-0 items-center gap-2 rounded-2xl px-3 py-2.5 text-left text-sm hover:bg-pale-blue" :class="tab===section.key?'bg-primary-container text-white hover:bg-primary-container':'text-on-surface'" @click="tab=section.key"><component :is="section.icon" class="h-4 w-4"/>{{ section.label }}</button></nav>
        <div class="min-w-0"><section v-if="store.settings[tab]" :class="card"><div class="mb-4"><h2 class="font-title-md text-title-md text-on-surface">{{ sections.find(x=>x.key===tab)?.label }}</h2><p class="text-xs text-on-surface-variant">Ubah nilai lalu simpan saat siap.</p></div><div class="grid gap-4 md:grid-cols-2"><div v-for="[key,label,description,kind,choices] in currentFields" :key="key" class="min-w-0 rounded-2xl border border-soft-blue p-4" :class="key==='maintenance_mode'?'bg-soft-orange':''"><div class="mb-3 flex flex-wrap items-start justify-between gap-2"><div class="min-w-0"><label :for="key" class="block font-label-sm text-label-sm text-on-surface">{{ label }}</label><p class="mt-1 text-xs text-on-surface-variant">{{ description }}</p></div><span v-if="store.meta[key]?.applied===false" class="rounded-full bg-surface-container-low px-2 py-1 text-[11px] text-on-surface-variant">Belum diterapkan</span></div><label v-if="kind==='boolean'" class="inline-flex cursor-pointer items-center gap-2 text-sm"><input :id="key" v-model="store.settings[tab][key]" type="checkbox" class="h-4 w-4 accent-blue-600"/>{{ store.settings[tab][key]?'Aktif':'Nonaktif' }}</label><div v-else-if="kind==='array'" class="flex flex-wrap gap-2"><label v-for="choice in choices" :key="choice" class="inline-flex cursor-pointer items-center gap-1 rounded-xl border border-soft-blue px-2 py-1 text-xs"><input type="checkbox" :checked="store.settings[tab][key].includes(choice)" @change="toggleArray(key,choice)"/>{{ choice }}</label></div><select v-else-if="kind==='select'" :id="key" v-model="store.settings[tab][key]" :class="input"><option v-for="choice in choices" :key="choice" :value="choice">{{ key==='default_user_role'?(choice===2?'2 · Siswa':'3 · Tutor'):choice }}</option></select><textarea v-else-if="kind==='textarea'" :id="key" v-model="store.settings[tab][key]" rows="3" :class="input"/><input v-else :id="key" v-model="store.settings[tab][key]" :type="kind" :class="input" @input="kind==='number' && (store.settings[tab][key]=$event.target.value===''?'':Number($event.target.value))"/></div></div></section>
          <section v-if="tab==='system'" :class="[card,'mt-5']"><div class="mb-3 flex items-center justify-between"><h2 class="font-title-md text-title-md text-on-surface">System Status</h2><button type="button" aria-label="Muat ulang status sistem" class="text-primary-container" @click="store.fetchSystemStatus()"><RefreshCw class="h-4 w-4"/></button></div><div class="grid gap-2 sm:grid-cols-2"><div v-for="[label,value] in statuses" :key="label" class="flex items-center justify-between gap-3 rounded-2xl bg-surface-container-low px-3 py-2 text-sm"><span>{{ label }}</span><span class="font-semibold text-primary-container">{{ value || '—' }}</span></div></div><p class="mt-3 text-xs text-on-surface-variant">Cloudinary menunjukkan konfigurasi tersedia, bukan hasil uji koneksi upload.</p></section>
        </div></div>
    </template>
  </div>
</template>
