<script setup>
import {reactive,ref,watch} from 'vue';
const props=defineProps({initial:{type:Object,default:null},saving:{type:Boolean,default:false}});
const emit=defineEmits(['submit']);
const form=reactive({title:'',description:'',subtest:'PU',category:'',file:null});
const error=ref('');
watch(()=>props.initial,item=>{form.title=item?.title||'';form.description=item?.description||'';form.subtest=item?.subtest||'PU';form.category=item?.category||'';form.file=null;},{immediate:true});
function save(){error.value='';if(form.title.trim().length<3||!form.category.trim()){error.value='Judul dan kategori wajib diisi.';return;}if(!props.initial&&!form.file){error.value='File materi wajib dipilih.';return;}emit('submit',{title:form.title.trim(),description:form.description.trim(),subtest:form.subtest,category:form.category.trim(),file:form.file});}
</script>
<template><form class="space-y-4 rounded-3xl border border-soft-blue bg-surface-white p-5 shadow-sm" @submit.prevent="save"><p v-if="error" role="alert" class="rounded-xl bg-danger-soft p-3 text-sm text-danger-rose">{{ error }}</p><label class="block text-sm font-semibold">Judul<input v-model="form.title" required minlength="3" maxlength="200" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"/></label><div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold">Subtes<select v-model="form.subtest" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"><option v-for="item in ['PU','PPU','PBM','PK','LBI','LBE','PM']" :key="item">{{ item }}</option></select></label><label class="block text-sm font-semibold">Kategori<input v-model="form.category" required maxlength="100" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"/></label></div><label class="block text-sm font-semibold">Deskripsi<textarea v-model="form.description" rows="4" maxlength="10000" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"/></label><label class="block text-sm font-semibold">File {{ initial?'(opsional untuk mengganti)':'' }}<input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt" :required="!initial" class="mt-1 block w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5 text-sm" @change="form.file=$event.target.files?.[0]||null"/><span class="mt-1 block text-xs font-normal text-on-surface-variant">PDF, Office, atau TXT · maksimal 20 MB</span></label><button type="submit" :disabled="saving" class="rounded-2xl bg-primary-container px-4 py-2.5 text-sm text-white disabled:opacity-50">{{ saving?'Menyimpan...':'Simpan Materi' }}</button></form></template>
