<script setup>
import { computed, reactive, ref, watch } from 'vue';
import { useQuestionDependenciesStore } from '~/stores/api/questionDependencies';
const props = defineProps({ initial: { type: Object, default: null }, saving: { type: Boolean, default: false } });
const emit = defineEmits(['submit']);
const dependencies = useQuestionDependenciesStore();
const subtests = [{code:'PU',name:'Penalaran Umum'},{code:'PPU',name:'Pengetahuan dan Pemahaman Umum'},{code:'PBM',name:'Pemahaman Bacaan dan Menulis'},{code:'PK',name:'Pengetahuan Kuantitatif'},{code:'LBI',name:'Literasi Bahasa Indonesia'},{code:'LBE',name:'Literasi Bahasa Inggris'},{code:'PM',name:'Penalaran Matematika'}];
const form = reactive({ title: '', description: '', subtests: [], category_ids: [], file: null });
const error = ref('');
const allSubtests = computed(() => form.subtests.length === subtests.length);
const groups = computed(() => Object.fromEntries(form.subtests.map(code => [code, dependencies.categories.filter(item => item.subtest === code)])));
const allCategories = computed(() => dependencies.categories.length && dependencies.categories.every(item => form.category_ids.includes(Number(item.id))));
async function refreshCategories() { await dependencies.fetchCategories(form.subtests); const allowed=new Set(dependencies.categories.map(item=>Number(item.id))); form.category_ids=form.category_ids.filter(id=>allowed.has(Number(id))); }
function toggleSubtest(code,checked){form.subtests=checked?[...new Set([...form.subtests,code])]:form.subtests.filter(item=>item!==code);refreshCategories();}
function toggleAllSubtests(checked){form.subtests=checked?subtests.map(item=>item.code):[];refreshCategories();}
function toggleCategory(id,checked){form.category_ids=checked?[...new Set([...form.category_ids,id])]:form.category_ids.filter(item=>item!==id);}
function toggleGroup(code,checked){const ids=(groups.value[code]||[]).map(item=>Number(item.id));form.category_ids=checked?[...new Set([...form.category_ids,...ids])]:form.category_ids.filter(id=>!ids.includes(id));}
function toggleAllCategories(checked){form.category_ids=checked?dependencies.categories.map(item=>Number(item.id)):[];}
watch(() => props.initial, async item => { form.title=item?.title||'';form.description=item?.description||'';form.subtests=item?.subtests?.map(entry=>entry.code)||[item?.subtest||'PU'];form.category_ids=item?.categories?.map(entry=>Number(entry.id))||(item?.category_id?[Number(item.category_id)]:[]);form.file=null;await refreshCategories(); }, { immediate:true });
function save(){error.value='';if(form.title.trim().length<3||!form.subtests.length||!form.category_ids.length){error.value='Judul, minimal satu subtes, dan minimal satu kategori wajib dipilih.';return;}if(!props.initial&&!form.file){error.value='File materi wajib dipilih.';return;}emit('submit',{title:form.title.trim(),description:form.description.trim(),subtests:[...form.subtests],category_ids:[...form.category_ids],file:form.file});}
</script>
<template><form class="space-y-4 rounded-3xl border border-soft-blue bg-surface-white p-5 shadow-sm" @submit.prevent="save">
  <p v-if="error" role="alert" class="rounded-xl bg-danger-soft p-3 text-sm text-danger-rose">{{ error }}</p>
  <label class="block text-sm font-semibold">Judul<input v-model="form.title" required minlength="3" maxlength="200" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"></label>
  <fieldset class="rounded-2xl border border-outline-variant p-4"><legend class="px-1 text-sm font-semibold">Subtes</legend><label class="mb-2 flex min-h-11 items-center gap-2 border-b border-soft-blue"><input type="checkbox" :checked="allSubtests" @change="toggleAllSubtests($event.target.checked)"><strong>Semua Subtes</strong></label><div class="grid gap-2 sm:grid-cols-2"><label v-for="item in subtests" :key="item.code" class="flex min-h-11 items-center gap-2 rounded-xl bg-surface-container-low px-3"><input type="checkbox" :checked="form.subtests.includes(item.code)" @change="toggleSubtest(item.code,$event.target.checked)"><span><strong>{{ item.code }}</strong><small class="ml-2 text-outline">{{ item.name }}</small></span></label></div></fieldset>
  <fieldset class="rounded-2xl border border-outline-variant p-4"><legend class="px-1 text-sm font-semibold">Kategori</legend><p v-if="!form.subtests.length" class="text-sm text-on-surface-variant">Pilih minimal satu subtes untuk menampilkan kategori.</p><template v-else><label class="mb-2 flex min-h-11 items-center gap-2 border-b border-soft-blue"><input type="checkbox" :checked="allCategories" @change="toggleAllCategories($event.target.checked)"><strong>Semua Kategori</strong></label><p v-if="dependencies.isLoadingCategories" class="text-sm text-outline">Memuat kategori...</p><div v-else class="space-y-3"><section v-for="code in form.subtests" :key="code" class="rounded-xl bg-surface-container-low p-3"><strong>{{ code }} · {{ subtests.find(item=>item.code===code)?.name }}</strong><p v-if="!groups[code]?.length" class="mt-2 text-xs text-outline">Belum ada kategori untuk subtes ini.</p><template v-else><label class="mt-2 flex min-h-10 items-center gap-2"><input type="checkbox" :checked="groups[code].every(item=>form.category_ids.includes(Number(item.id)))" @change="toggleGroup(code,$event.target.checked)">Semua Kategori {{ code }}</label><div class="grid sm:grid-cols-2"><label v-for="item in groups[code]" :key="item.id" class="flex min-h-10 items-center gap-2"><input type="checkbox" :checked="form.category_ids.includes(Number(item.id))" @change="toggleCategory(Number(item.id),$event.target.checked)">{{ item.name }}</label></div></template></section></div></template></fieldset>
  <label class="block text-sm font-semibold">Deskripsi<textarea v-model="form.description" rows="4" maxlength="10000" class="mt-1 w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5"></textarea></label>
  <label class="block text-sm font-semibold">File {{ initial?'(opsional untuk mengganti)':'' }}<input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt" :required="!initial" class="mt-1 block w-full rounded-2xl border border-outline-variant bg-surface-container-low px-3 py-2.5 text-sm" @change="form.file=$event.target.files?.[0]||null"><span class="mt-1 block text-xs font-normal text-on-surface-variant">PDF, Office, atau TXT · maksimal 20 MB</span></label>
  <button type="submit" :disabled="saving" class="rounded-2xl bg-primary-container px-4 py-2.5 text-sm text-white disabled:opacity-50">{{ saving?'Menyimpan...':'Simpan Materi' }}</button>
</form></template>
